Update docker script files

diff --git a/docker/docker_build b/docker/docker_build
--- a/docker/docker_build
+++ b/docker/docker_build
@@ -1,4 +1,10 @@
-# $1 is the token, $2 is the repo tag
+# $1 is the token
+# $2 is the repo tag
+# $3 is the repo URL of your repository
+if [ "$#" -ne 3 ]; then
+    echo "Error: Exactly 3 parameters are required. "
+    exit 1
+fi
 RUNNER_NAME=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
 REPO_TAG="$2.$RUNNER_NAME"
 REPO_URL=$3
